
import { GoogleGenAI } from "@google/genai";
import { AspectRatio } from "../types";

// IMPORTANT: This service assumes the Gemini API key is available in the environment variables.
// In a real application, this should be handled securely on a backend server.
const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, you might want to show a more user-friendly error.
  // For this example, we log a warning but allow the app to run,
  // as the user might not use the image generation feature.
  console.warn("Gemini API key not found. Image generation will not work.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });

export const generateImage = async (prompt: string, aspectRatio: AspectRatio): Promise<string> => {
  if (!API_KEY) {
    throw new Error("API Key is not configured. Cannot generate image.");
  }
  
  try {
    console.log(`Generating image with prompt: "${prompt}" and aspect ratio: ${aspectRatio}`);
    
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: aspectRatio,
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    throw new Error("Failed to generate image. Please try again.");
  }
};
